version: 2
updates:
  # npm Dependencies überwachen
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 5
    reviewers:
      - 'Gokujo'
    assignees:
      - 'Gokujo'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'security'
      - 'automated'
    ignore:
      # Ignoriere Major Updates für kritische Dependencies
      - dependency-name: 'vue'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vue-router'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vue-i18n'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']

  # GitHub Actions überwachen
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 3
    reviewers:
      - 'Gokujo'
    assignees:
      - 'Gokujo'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'automated'
